### PR TITLE
Type to complete uniqname

### LINKED ISSUE #15: Type to complete group
While the picker works OK for selecting among courses or projects, it's not a great solution for selecting a group.  It would be great if the user could start typing a uniqname and the list of groups would dynamically shrink.

### PR DESCRIPTION
**Pull request by awdeorio**
Type to complete uniqname using readline library.

Closes #15

This is a work in progress.

### CODE REVIEW

**Comment by awdeorio** [comment]
Looking for feedback on this draft.  Try the group selection tab-completion and let me know what you think @japplefield .

**Comment by japplefield** [comment]
I like this a lot. Should the same kind of behavior apply to course/project selection too? (i.e. completely replacing the picker) I do not believe it is necessary but curious what your thoughts are.

**Comment by awdeorio** [comment]
> Should the same kind of behavior apply to course/project selection too? (i.e. completely replacing the picker) I do not believe it is necessary but curious what your thoughts are.

I think the picker still makes sense for the course and project selection

**Comment by awdeorio** [comment]
@japplefield would you mind taking a look and reviewing?

**Review by japplefield — APPROVED** [review]
LGTM (sorry for the delay!)

**Pull request merged**
