### PR TITLE
Add flag to download groups in OH-queue-friendly format

### LINKED ISSUE #34: Download groups in OH-queue-friendly format
`$ agio groups --list` downloads in a format that looks like this:

```console
[299866] achitta
[300195] chenmar, yuntongz
...
```

Very readable, but the OH queue expects a JSON that looks like this:

```json
[["nuppula@umich.edu","sarangia@umich.edu","svejp@umich.edu"],
["bybwang@umich.edu","chungwil@umich.edu","marxd@umich.edu"],
["nksuram@umich.edu"]]
```

Add a setting that formats the group list like this for easy copy-pasting into the OH queue
Bonus points: an extension that also makes a `PUT` to `https://eecsoh.eecs.umich.edu/api/queues/<queue-id>/groups` with groups directly from the Autograder. ([OH Queue source code](https://github.com/CarsonHoffman/office-hours-queue))

### PR DESCRIPTION
**Pull request by japplefield**
Closes #34 

Try it out!

```console
$ agio groups -q
```

### CODE REVIEW

**Comment by japplefield** [comment]
> EDIT: what do you think about `--list-queue` or maybe `--list-json` instead of `--queue`?

I'm fine with `--list-queue`

**Comment by awdeorio** [comment]
How about adding a unit test that's similar to the one for `groups --list`?

**Comment by japplefield** [comment]
@awdeorio In your refactor you removed some logic that explicitly filters out users not on the students list for the course the project belongs to. This solves an issue that I hadn't thought of which is that previously, all users would be filtered out before we uploaded a class roster. But this also creates an issue (?) that staff members will be included in the output, which I think we don't want when uploading groups to the OH queue??? (I'm not really sure if this matters, do you have any idea/thoughts?)

**Comment by awdeorio** [comment]
> But this also creates an issue (?) that staff members will be included in the output, which I think we don't want when uploading groups to the OH queue??? 

I didn't think of that!  If this is indeed an issue, then maybe it might make sense to add a flag to the `agio groups --students-only`.  However, if the OH queue doesn't care, then maybe its fine to leave it as-is.

**Comment by japplefield** [comment]
> I didn't think of that! If this is indeed an issue, then maybe it might make sense to add a flag to the `agio groups --students-only`. However, if the OH queue doesn't care, then maybe its fine to leave it as-is.

After OH yesterday, seems like the queue doesn't care.

**Review by awdeorio — APPROVED** [review]
LGTM.  Would you be ok with calling the option `--list-json` instead of `--queue`?

**Comment by japplefield** [comment]
> LGTM. Would you be ok with calling the option `--list-json` instead of `--queue`?

Yep I'm good with that.

**Pull request merged**
