### PR TITLE
Publish to PyPI

### LINKED ISSUE #2: Publish to PyPI
- [x] Make sure README Quick Start is up-to-date
- [x] Create a `develop` branch and make it the GitHub default
- [x] Make this repo public
- [x] Document release procedure
- [x] Publish to PyPI

### PR DESCRIPTION
**Pull request by awdeorio**
Publish to PyPI.

Closes #2

## Validation
- GitHub repo should be public https://github.com/eecs485staff/agio-cli
- PyPI should be live https://pypi.org/project/agiocli/
- Install from PyPI into a clean virtual environment using instructions in the README

### CODE REVIEW

**Comment by japplefield** [comment]
```console
jmapple@Justins-MacBook-Pro agio-test % python3 -m venv env
jmapple@Justins-MacBook-Pro agio-test % source env/bin/activate
(env) jmapple@Justins-MacBook-Pro agio-test % pip install agiocli
Collecting agiocli
  Using cached agiocli-0.1.0-py3-none-any.whl (12 kB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting click
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting pick
  Using cached pick-1.0.0-py2.py3-none-any.whl (5.5 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.3-py3-none-any.whl (35 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, pick, click, agiocli
Successfully installed agiocli-0.1.0 certifi-2021.5.30 charset-normalizer-2.0.3 click-8.0.1 idna-3.2 pick-1.0.0 requests-2.26.0 urllib3-1.26.6
(env) jmapple@Justins-MacBook-Pro agio-test % agio -h
Traceback (most recent call last):
  File "/Users/jmapple/Developer/agio-test/env/bin/agio", line 5, in <module>
    from agiocli.__main__ import main
  File "/Users/jmapple/Developer/agio-test/env/lib/python3.9/site-packages/agiocli/__init__.py", line 4, in <module>
    from .utils import *
  File "/Users/jmapple/Developer/agio-test/env/lib/python3.9/site-packages/agiocli/utils.py", line 11, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
```

Should `setup.py` be modified to require `python-dateutil`?

**Comment by awdeorio** [comment]
Good catch!  Fixed 00ea4a499d0e01f272735808733aac74c3c14b1c

**Comment by japplefield** [comment]
Fixed tiny typo in README, does it automatically get updated on PyPI when the PR is merged?

**Review by japplefield — APPROVED** [review]

**Comment by awdeorio** [comment]
> Does it automatically get updated on PyPI when the PR is merged? Otherwise LGTM.

Nope, that's a manual process

**Pull request merged**
